"""Add Zitadel integration

Revision ID: 7f0d4b46bcf0
Revises: 
Create Date: 2025-11-29 10:56:02.071881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0d4b46bcf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # Prüfe ob zitadel_user_id bereits existiert
        try:
            batch_op.add_column(sa.Column('zitadel_user_id', sa.String(length=255), nullable=True))
        except Exception:
            # Spalte existiert bereits, ignoriere Fehler
            pass
        
        # Prüfe ob password_hash nullable ist
        try:
            batch_op.alter_column('password_hash',
                   existing_type=sa.VARCHAR(length=255),
                   nullable=True)
        except Exception:
            # Bereits nullable oder anderer Fehler, ignoriere
            pass
        
        # Prüfe ob is_admin nullable=False ist
        try:
            batch_op.alter_column('is_admin',
                   existing_type=sa.BOOLEAN(),
                   nullable=False,
                   existing_server_default=sa.text('0'))
        except Exception:
            # Bereits korrekt konfiguriert, ignoriere
            pass
        
        # Erstelle Index nur wenn nicht vorhanden
        try:
            batch_op.create_index(batch_op.f('ix_users_zitadel_user_id'), ['zitadel_user_id'], unique=True)
        except Exception:
            # Index existiert bereits, ignoriere
            pass
        
        # Lösche role-Spalte nur wenn sie existiert
        try:
            batch_op.drop_column('role')
        except Exception:
            # Spalte existiert nicht, ignoriere Fehler
            pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_zitadel_user_id'))
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('zitadel_user_id')

    # ### end Alembic commands ###
